### ISSUE TITLE
Establish feature parity with old Docker image

### ISSUE THREAD

**Issue by matthew-levan** [urbit/vere#121] opened 2023-01-18 08:40 UTC
The Docker image we currently build and upload to [tloncorp/vere](https://hub.docker.com/r/tloncorp/vere) on Docker Hub doesn't work like the old one (i.e., from 1.15 and earlier in the [urbit/urbit](https://github.com/urbit/urbit) monorepo) does. The new image at least omits the following features, which many have come to rely on for their operations:
1. Automatic boot with keyfile (if it's present in a mounted Docker volume and no pier exists)
2. Automatic boot from pier (again, if present in a mounted volume)

The [script](https://github.com/urbit/urbit/blob/d8ca6063af3d510ad350edf7bfbdb38f40da3984/nix/pkgs/docker-image/default.nix) in the monorepo contains all of the old logic. We should take the opportunity to port over all the features from this script and also review the Docker image's documentation in [DOCKER.md](DOCKER.md) to ensure clarity and accuracy.

Related: #118.

**Comment by mcevoypeter** [comment] 2023-01-18 17:03
This is a duplicate of #112, which describes the behavior associated with the lack of feature parity.

**Closed by mcevoypeter** 2023-01-18 17:03 UTC
Labels: duplicate
