### ISSUE TITLE
unable to start docker v1.16-live image 

### ISSUE THREAD

**Issue by tomholford** [urbit/vere#112] opened 2023-01-13 22:36 UTC
# Context

I use a `docker-compose` config like so:
```yml
  datder-sonnet:
    image: tloncorp/urbit:v1.15
    restart: unless-stopped
    ports:
      - "8080:80"
      - "34343:34343/udp"
    volumes:
      - ~/urbit/datder-sonnet:/urbit/datder-sonnet
    networks:
      - web
    stdin_open: true
    tty: true
    depends_on:
      - caddy
      - minio
```

When I change the `image` value to `tloncorp/vere:v1.16-live` and run `docker-compose up`, the new image is downloaded, but the instance enters a reboot loop with the following output over and over:

```
Urbit: a personal server operating function
https://urbit.org
Version 1.16

Usage: /app/pkg/vere/urbit [options...] ship_name
where ship_name is a @p phonetic representation of an urbit address
without the leading '~', and options is some subset of the following:

-A, --arvo DIR                Use dir for initial clay sync
-a, --abort                   Abort aggressively
-B, --bootstrap PILL          Bootstrap from this pill
-b, --http-ip IP              Bind HTTP server to this IP address
-C, --memo-cache-limit LIMIT  Set memo cache max size; 0 means uncapped
-c, --pier PIER               Create a new urbit in pier/
-D, --replay                  Recompute from events
-d, --daemon                  Daemon mode; implies -t
-e, --ethereum URL            Ethereum gateway
-F, --fake SHIP               Fake keys; also disables networking
-G, --key-string STRING       Private key string (@uw, see also -k)
-g, --gc                      Set GC flag
-I, --inject FILE             Inject event from jamfile
-i, --import FILE             Import pier state from jamfile
-J, --ivory-pill PILL         Use custom ivory pill
-j, --json-trace              Create json trace file in .urb/put/trace
-K, --kernel-stage STAGE      Start at Hoon kernel version stage
-k, --key-file KEYS           Private key file (see also -G)
-L, --local                   Local networking only
    --loom                    Set loom to binary exponent (31 == 2GB)
-l, --lite-boot               Most-minimal startup
-n, --replay-to NUMBER        Replay up to event
-P, --profile                 Profiling
-p, --ames-port PORT          Set the ames port to bind to
    --http-port PORT          Set the http port to bind to
    --https-port PORT         Set the https port to bind to
-q, --quiet                   Quiet
-R, --versions                Report urbit build info
-r, --replay-from NUMBER      Load snapshot from event
-S, --skip-battery-hashes     Disable battery hashing
-t, --no-tty                  Disable terminal/tty assumptions
-u, --bootstrap-url URL       URL from which to download pill
-v, --verbose                 Verbose
-w, --name NAME               Boot as ~name
-X, --scry PATH               Scry, write to file, then exit
-x, --exit                    Exit immediately
-Y, --scry-into FILE          Optional name of file (for -X)
-Z, --scry-format FORMAT      Optional file format ('jam', or aura, for -X)
    --no-conn                 Do not run control plane
    --no-dock                 Skip binary "docking" on boot

Development Usage:
   To create a development ship, use a fakezod:
   /app/pkg/vere/urbit -F zod -A /path/to/arvo/folder -B /path/to/pill -c zod

   For more information about developing on urbit, see:
   https://github.com/urbit/urbit/blob/master/CONTRIBUTING.md

Simple Usage: 
   /app/pkg/vere/urbit -c <my-comet> to create a comet (anonymous urbit)
   /app/pkg/vere/urbit -w <my-planet> -k <my-key-file> if you own a planet
   /app/pkg/vere/urbit <my-planet or my-comet> to restart an existing urbit
utilities:
  /app/pkg/vere/urbit cram <pier>               jam state:
  /app/pkg/vere/urbit dock <pier>               copy binary:
  /app/pkg/vere/urbit grab <pier>               measure memory usage:
  /app/pkg/vere/urbit info <pier>               print pier info:
  /app/pkg/vere/urbit meld <pier>               deduplicate snapshot:
  /app/pkg/vere/urbit pack <pier>               defragment snapshot:
  /app/pkg/vere/urbit prep <pier>               prepare for upgrade:
  /app/pkg/vere/urbit next <pier>               request upgrade:
  /app/pkg/vere/urbit queu <pier> <at-event>    cue state:
  /app/pkg/vere/urbit vere ARGS <output dir>    download binary:

  run as a 'serf':
    /app/pkg/vere/urbit serf <pier> <key> <flags> <cache-size> <at-event>
```

For reference, here's the output I see for the previous container image:

```
~
urbit 1.15
boot: home is /urbit/datder-sonnet
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.310.146.560
boot: installed 351 jets
vere: checking version compatibility
ames: live on 34343
conn: listening on /urbit/datder-sonnet/.urb/conn.sock
```

**Comment by mcevoypeter** [comment] 2023-01-18 17:04
The reason for this issue can be found in #121, which has been marked as a duplicate of this one.

**Closed** 2023-01-18 17:24 UTC
Labels: bug, build
